[project]
name = "rpa-excel-ui-automation"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "merzamac", email = "100945727+merzamac@users.noreply.github.com"},
]
dependencies = ["uiautomation>=2.0.29", "loguru>=0.7.3"]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[tool.pdm]
distribution = true

[tool.pdm.scripts]
start = { cmd = "python -m rpa_excel_ui_automation.app", help = "Ejecuta el flujo RPA completo (abrir origen y guardar como)" }

[dependency-groups]
dev = [
    "openpyxl>=3.1.5",
    "pytest>=9.1.1",
]
